apiVersion: v1
kind: List
metadata:
  name: simple-mysql
  namespace: test
  annotations:
    description: This template defines objects that are required to spin up an simple-mysql service pod
    tags: simple-mysql, service
    openshift.io/display-name: simple-mysql-template
    openshift.io/long-description: This template provides objects that are required to spin up a simple-mysql service pod.
    openshift.io/provider-display-name: Norbel Ambanumben
labels:
  app: simple-mysql-app
  createdBy: Norbel Ambanumben
items:
  -
    apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: simple-mysql
    spec:
      strategy:
        type: Rolling
        rollingParams:
          updatePeriodSeconds: 1
          intervalSeconds: 1
          timeoutSeconds: 600
          maxUnavailable: 25%
          maxSurge: 25%
        resources:
      replicas: "1"
      template:
        metadata:
          labels:
            app: simple-mysql
        spec:
          containers:
            - name: simple-mysql
              image: docker.io/aanorbel/spring-openshift-mysql
              imagePullPolicy: Always
              env:
                - name: SPRING_DATASOURCE_URL
                  value: jdbc:mysql://172.30.68.129:3306/simplemysql
                - name: SPRING_DATASOURCE_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mysql-persistent-8n2hx-credentials-v8pwh
                      key: username
                - name: SPRING_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-persistent-8n2hx-credentials-v8pwh
                      key: password
              ports:
                - name: http
                  containerPort: "8080"
  -
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: simple-mysql
      name: simple-mysql
    spec:
      selector:
        app: simple-mysql
      type: LoadBalancer
      ports:
        - name: http
          port: "8080"
  -
    apiVersion: v1
    kind: Route
    metadata:
      name: simple-mysql
    spec:
      to:
        kind: Service
        name: simple-mysql
        weight: "100"
      port:
        targetPort: "http"
      wildcardPolicy: None